export const SESSION_EVENT_TYPES = {
  SESSION_CREATED: "SESSION_CREATED",
  QUESTION_ASSIGNED: "QUESTION_ASSIGNED",
  INTERVIEW_READY: "INTERVIEW_READY",
  INTERVIEW_ROOM_OPENED: "INTERVIEW_ROOM_OPENED",
  LISTENING_STARTED: "LISTENING_STARTED",
  LISTENING_STOPPED: "LISTENING_STOPPED",
  QUESTION_SHOWN: "QUESTION_SHOWN",
  STAGE_ADVANCED: "STAGE_ADVANCED",
  CANDIDATE_SPOKE: "CANDIDATE_SPOKE",
  CANDIDATE_TURN_AUTOSUBMITTED: "CANDIDATE_TURN_AUTOSUBMITTED",
  AI_SPOKE: "AI_SPOKE",
  AI_INTERRUPTED_BY_CANDIDATE: "AI_INTERRUPTED_BY_CANDIDATE",
  HINT_REQUESTED: "HINT_REQUESTED",
  CODE_SNAPSHOT_SAVED: "CODE_SNAPSHOT_SAVED",
  CODE_RUN_REQUESTED: "CODE_RUN_REQUESTED",
  CODE_RUN_COMPLETED: "CODE_RUN_COMPLETED",
  INTERVIEW_ENDED: "INTERVIEW_ENDED",
  EVALUATION_STARTED: "EVALUATION_STARTED",
} as const;

export type SessionEventType = (typeof SESSION_EVENT_TYPES)[keyof typeof SESSION_EVENT_TYPES];
